{
  #LM Model args
  "lm_name": "gpt2-large",
  "ref_lm_name": "gpt2-large",
  "tk_name": "gpt2-large",
  "num_layers_unfrozen": 2,
  "save_model": True,
  "save_folder": 'ckpts/roc_evil_coop_model/',
  "use_lm_ckpt": True,
  "lm_ckpt_path": "/home/ubuntu/alex/pref_learning/ControlledCarp/ckpts/raw-roc-gpt2-large/",
  "tokenizer_path": "/home/ubuntu/alex/pref_learning/ControlledCarp/ckpts/imagination_gpt2_tokenizer/",

  #Carp model args
  "carp_version": "coop",
  "carp_config_path": "/home/ubuntu/alex/pref_learning/magiCARP/configs/coop/alignment_coop.yml",
  "carp_ckpt_path": "/home/ubuntu/alex/pref_learning/magiCARP/ckpts/New Alignment CoOp Carp L/",

  #Training args
  "steps": 20000,
  "batch_size": 32,
  "forward_batch_size": 16,

  #PPO Args
  "ppo_epochs": 4,
  "txt_in_len": 14,
  "txt_out_len": 60,
  "lr": 5.0e-6,
  "init_kl_coef":0.2,
  "target": 25,   #KL Divergence target
  "horizon":10000,
  "gamma":1,   #Discount factor
  "lam":0.95,
  "cliprange": .2,
  "cliprange_value":.2,
  "vf_coef":.15,

  #Review
  "review": "evil",

  #Dataset
  "data_path": "dataset/circle_prompts.txt",

  #Logging
  'LOG': True,

  #Evaluation
  'EVAL': True,
  "num_eval_examples": 10,

  #Minimize or maximize
  'minimize': False,
}